### PR TITLE
Refactor ErrorHandler and add time when error occurred 

### PR DESCRIPTION
**Pull request by titkov49**
Changes:
- Remove react-ace and replace it with common html
- Add time state (when error occurred)
- Render time in DateTime component

### CODE REVIEW

**Comment by titkov49** [comment]
Screenshot 2021-11-01 at 15 44 15
Screenshot 2021-11-01 at 15 45 15
Screenshot 2021-11-01 at 15 45 27

**Comment by titkov49** [comment]
@ateska @Pe5h4 review please :)

**Review by Pe5h4 — CHANGES_REQUESTED** [review]
Looks cool, but could you please remove `react-ace` and `ace-builds` from the package.json of demo app, that it is not necessarily used?
https://github.com/TeskaLabs/asab-webui/blob/refactor/error-handler/demo/package.json#L42
 https://github.com/TeskaLabs/asab-webui/blob/refactor/error-handler/demo/package.json#L51

**Review by ateska — APPROVED** [review]

**Comment by titkov49** [comment]
> Looks cool, but could you please remove `react-ace` and `ace-builds` from the package.json of demo app, that it is not necessarily used? https://github.com/TeskaLabs/asab-webui/blob/refactor/error-handler/demo/package.json#L42 https://github.com/TeskaLabs/asab-webui/blob/refactor/error-handler/demo/package.json#L51

Yes, sure. Completely forgot about it. Thank you

**Pull request merged**
