### PR TITLE
INDG-217 - Accelerate the loading speed of the application with lazy (gradual) loading

### PR DESCRIPTION
**Pull request by titkov49**
CHANGES:
-Added React.Suspense in Application.js
-Added Loading Spinner
-Added dynamic imports in demo/HomeContainer.js

### CODE REVIEW

**Comment by ateska** [comment]
Looks good but I need some kind of metrics in order to proceed with this review.

**Review by ateska — CHANGES_REQUESTED** [review]
Looks good but I need some kind of metrics in order to proceed with this review.

**Comment by titkov49** [comment]
@ateska after builduing seacat-webui main.js file size is reduced from 1252 kB to 1124 kB. Other 25 chunks is in range from 2 kB to 30 kB... I'm still trying to find a way to optimize our application more.

**Comment by titkov49** [comment]
@ateska 
Fixed bug with importing scss and css which was crashing some pages after building process

**Comment by ateska** [comment]
Ok, good.
1124 kB is still a lot - we need to employ compression etc.

**Comment by Pe5h4** [comment]
@ateska Will be compression done through nginx? https://docs.nginx.com/nginx/admin-guide/web-server/compression/?_ga=2.197382956.2017845742.1618920973-1218105409.1618920973

**Comment by ateska** [comment]
> @ateska Will be compression done through nginx? https://docs.nginx.com/nginx/admin-guide/web-server/compression/?_ga=2.197382956.2017845742.1618920973-1218105409.1618920973

Yes, it should be. Robin has this in the sprint.

**Comment by titkov49** [comment]
@ateska So can we merge this PR?

**Review by ateska — APPROVED** [review]

**Pull request merged**
