### PR TITLE
New design/fix styles

### PR DESCRIPTION
**Pull request by Aringoaway**
return translations for Sidebar and Breadcrumbs. Fix dropdown styles

### CODE REVIEW

**Comment by Aringoaway** [comment]
asab-webui-translation

**Comment by Pe5h4** [comment]
@Aringoaway Please write to the description of this PR, that it is about implementing back the lost translations for Sidebar and Breadcrumbs, then it can be merged, if there will be no conflicts

**Comment by Aringoaway** [comment]
Fix dropdown styles, it work correct in DataTable and Card
dropdown-styles

**Comment by Aringoaway** [comment]
@Pe5h4 I fixed dropdown styles, they slill work on all DataTable, Card and dropdown in Header
dropdown-all

**Review by Pe5h4 — APPROVED** [review]
This looks fine

**Pull request merged**
