### PR TITLE
Microservices container refactorisation with websocket

### PR DESCRIPTION
**Pull request by Pe5h4**
## Refactorisation of Microservices container to Services and implement websocket connection

- refactorisation of microservices container >> renamed to Services
- created a custom table with the list of services
- implemented websocket connection for receiving data
- implemented action buttons to trigger actions within the services

### CODE REVIEW

**Comment by Pe5h4** [comment]
@ateska This is a 1st iteration of Instances implementation (microservices refactorisation) where has been done:

- microservices container was renamed to `Instances`
- websocket connection implemented (with proper data handling of delta and full frames)
- custom table with nested table  with detail information was introduced
- implemented action buttons to trigger instances actions

I think as a first iteration, this can be enough for eventual test/production deployments, whenever @eliska-n will be satisfied with her cool remote-control service

instances-ui-websocket-table

instances-ui-websocket-table2

**Review by ateska — APPROVED** [review]
Looks cool!

**Comment by eliska-n** [comment]
:pig: :heart:

**Comment by ateska** [comment]
@Pe5h4 "Instances" is not an intuitive name for this screen.
It is more "Services" or "Cluster"

**Comment by Pe5h4** [comment]
@ateska Renamed to `Services`
Selection_093

**Pull request merged**
