### PR TITLE
Fix crush app customCellStyle

### PR DESCRIPTION
**Pull request by Aringoaway**
The variable customCellStyles was be a `const` because of it, in app, I have this Error 
image

I changed `const` to `let`

### CODE REVIEW

**Comment by Pe5h4** [comment]
@Aringoaway When this error appears? What you need to set to get this?

**Comment by Aringoaway** [comment]
@Pe5h4 You need to use `customCellStyle` in component when you use DataTable

**Review by Pe5h4 — APPROVED** [review]
@Aringoaway Oh, I see

**Comment by Pe5h4** [comment]
@petrKavulok ^^^ Fyi I think this is a correction of your changes here: https://github.com/TeskaLabs/asab-webui/pull/337

**Comment by petrKavulok** [comment]
> @petrKavulok ^^^ Fyi I think this is a correction of your changes here: #337
jj, this has been discussed with Ari

**Pull request merged**
