### PR TITLE
Change "?" in HelpButton to word "Help"

### PR DESCRIPTION
**Pull request by aringocode**
### Changes
1. change icon to text
2. update Changelog

image
image

### CODE REVIEW

**Review by Pe5h4 — APPROVED** [review]
Not sure about this change, but if Aviva insisted on changing it from `?` to `Help`...

**Comment by ateska** [comment]
I propose "Documentation" ...

**Comment by aringocode** [comment]
> I propose "Documentation" ...

 I could, of course, use "documentation." But that's a very long word. Aviva suggested "Help" or "Support".

**Comment by aringocode** [comment]
@ateska ^^^

**Comment by ateska** [comment]
Ok, let's stick with "Help".

We use "Docs" on teskalabs.com

**Pull request merged**
