### PR TITLE
New-design-lmio-fix-styles

### PR DESCRIPTION
**Pull request by Aringoaway**
fix color in sidebar and dropdown header hover in darkmode, fix dropdown in configuration, pagination

### CODE REVIEW

**Comment by Aringoaway** [comment]
lmio-fix-sidebar

**Comment by Aringoaway** [comment]
header-dropdown

**Comment by Aringoaway** [comment]
configuration-dropdown

**Comment by Aringoaway** [comment]
config-drpdwn

**Comment by Aringoaway** [comment]
lmio-office

**Comment by Aringoaway** [comment]
@Pe5h4 can you review it pls

**Comment by Aringoaway** [comment]
remove margin
image

**Review by Pe5h4 — APPROVED** [review]

**Comment by Aringoaway** [comment]
@Pe5h4  I fix this bug
image

**Pull request merged**
