### PR TITLE
Sidebar autoclose on small screens 

### PR DESCRIPTION
**Pull request by titkov49**

### CODE REVIEW

**Comment by titkov49** [comment]
https://user-images.githubusercontent.com/37152497/149743521-d81ed600-ff4c-452c-986a-114c05ecae1b.mov

**Review by Pe5h4 — APPROVED** [review]
Looks good to me, just implement that grayish foreground for a main container when sidebar is open on small screens and overlaps the content of the container. It should also disable clicking on the main container as we spoke of on standup

**Comment by titkov49** [comment]
@Pe5h4 this is it, right? 

https://user-images.githubusercontent.com/37152497/149754326-e45bd4be-c0d7-43f3-af99-9d518232a565.mov

**Comment by Pe5h4** [comment]
@titkov49 yep

> @Pe5h4 this is it, right?
> Screen.Recording.2022-01-17.at.11.36.59.mov

**Comment by ateska** [comment]
Looks cool.

**Review by ateska — APPROVED** [review]

**Pull request merged**
