### PR TITLE
Add AttentionCard component into MicroserviceDetailContainer

### PR DESCRIPTION
**Pull request by titkov49**
Instead of using `react-json-viewer` component `JSONTable` component was created in order to skip indexes in parent table and to render dates with `DateTime` component.
Screenshot 2021-09-10 at 15 31 52

Screenshot 2021-09-10 at 15 30 58

### CODE REVIEW

**Comment by titkov49** [comment]
@ateska @Pe5h4 review please

**Review by Pe5h4 — APPROVED** [review]
Looks good!

**Comment by Pe5h4** [comment]
We might do a reusable component from that in the next iterations

**Comment by ateska** [comment]
Yes, I agree ... this looks cool.

**Review by ateska — APPROVED** [review]

**Pull request merged**
