### PR TITLE
Move sidebar about item near collapse button

### PR DESCRIPTION
**Pull request by titkov49**
Make About nav item and collapse sidebar button on one line (like it is done in JIRA)

### CODE REVIEW

**Comment by titkov49** [comment]
Screenshot 2021-11-04 at 14 59 53
Screenshot 2021-11-04 at 14 59 58
Screenshot 2021-11-04 at 15 00 03
Screenshot 2021-11-04 at 15 00 07
Screenshot 2021-11-04 at 15 00 28
Screenshot 2021-11-04 at 15 00 33

**Comment by titkov49** [comment]
@ateska @Pe5h4 review please

**Review by ateska — CHANGES_REQUESTED** [review]
Can the  "About" text be white (same as the normal sidebar item)?

**Review by Pe5h4 — APPROVED** [review]

**Comment by titkov49** [comment]
> Can the "About" text be white (same as the normal sidebar item)?

Yeah, sure

**Comment by titkov49** [comment]
@ateska
STATES
1: About item is not active and not on hover
2: About item is not active but on hover
3: About item is active but not on hover
4: About item is active and on hover

Screenshot 2021-11-04 at 23 40 06
Screenshot 2021-11-04 at 23 41 18
Screenshot 2021-11-04 at 23 43 16
Screenshot 2021-11-04 at 23 43 58

**Comment by titkov49** [comment]
@ateska @Pe5h4 
btw should first column on third row be empty?

Screenshot 2021-11-04 at 23 43 58

**Review by ateska — APPROVED** [review]

**Pull request merged**
